# Generated by Django 4.2.1 on 2024-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('add', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(choices=[('IT', 'IT'), ('FINANCE', 'FINANCE')], max_length=50)),
            ],
        ),
    ]
